### ISSUE TITLE
Reference to TIMES-DK

### ISSUE THREAD

**Issue by olejandro** [NordicEnergyResearch/NCES2020#2]
Currently https://www.esymodels.man.dtu.dk/times-dk is used as a reference to TIMES-DK which does not provide much information about the model. Please refer to the  open access paper documenting the model and available at https://doi.org/10.1016/j.esr.2018.11.003 in addition / instead.

**Comment by MikkelBosack** [comment]
I have added the changes to the review process

**Comment by olejandro** [comment]
Great, thanks! Btw, one can use key words like closes and a reference to an issue in pull requests, to tell github to close the issue if the pull request is accepted. E.g. for this issue one could use Closes #2.
