### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by olejandro** [NordicEnergyResearch/NCES2020#3]
Currently  ON-TIMES is available under GPL-3.0 License which is a commonly used license for open source software. However a TIMES model (including ON-TIMES) is essentially a dataset/database, so an open source license like [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/) which takes into account database specifics may be more appropriate.

**Comment by olejandro** [comment]
Also [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) may be a good choice as it requires distribution of modifications under the same license as the original work.

**Comment by tilseb** [comment]
Thanks for the suggestion. I agree, it should be a copyleft type. According to [openmod](https://wiki.openmod-initiative.org/wiki/Choosing_a_license), CC BY-SA is more for documentation. Thus, if the license should be changed, I suggest to go for [ODbl](https://opendatacommons.org/licenses/odbl/) instead.
